"""assessment_protocols_and_rom

Revision ID: 6d49ba3c72e9
Revises: 8b3675a1a316
"""

import sqlalchemy as sa
from alembic import op

revision = "6d49ba3c72e9"
down_revision = "8b3675a1a316"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "protocol_categories",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "protocols",
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column("category_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["protocol_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "protocol_versions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("protocol_id", sa.String(length=60), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["protocol_id"],
            ["protocols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("protocol_id", "version"),
    )
    op.create_index(
        op.f("ix_protocol_versions_protocol_id"),
        "protocol_versions",
        ["protocol_id"],
        unique=False,
    )
    op.create_table(
        "assessment_protocols",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=100), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["protocol_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_id"),
    )
    op.create_table(
        "protocol_steps",
        sa.Column("id", sa.String(length=140), nullable=False),
        sa.Column("version_id", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["protocol_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "key"),
    )
    op.create_index(
        op.f("ix_protocol_steps_version_id"),
        "protocol_steps",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "rom_sessions",
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("movement", sa.String(length=40), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.PrimaryKeyConstraint("assessment_id"),
    )
    op.create_table(
        "assessment_step_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_protocol_id", sa.String(length=36), nullable=False),
        sa.Column("step_key", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("child_assessment_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_protocol_id"],
            ["assessment_protocols.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_protocol_id", "step_key"),
        sa.UniqueConstraint("child_assessment_id"),
    )
    op.create_index(
        op.f("ix_assessment_step_results_assessment_protocol_id"),
        "assessment_step_results",
        ["assessment_protocol_id"],
        unique=False,
    )
    op.create_table(
        "rom_measurements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("measurement_id", sa.String(length=36), nullable=False),
        sa.Column("movement", sa.String(length=40), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("minimum", sa.Float(), nullable=False),
        sa.Column("maximum", sa.Float(), nullable=False),
        sa.Column("excursion", sa.Float(), nullable=False),
        sa.Column("peak_value", sa.Float(), nullable=False),
        sa.Column("peak_frame_index", sa.Integer(), nullable=False),
        sa.Column("peak_timestamp_ms", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["measurement_id"],
            ["biomechanical_measurements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("measurement_id"),
    )
    op.create_index(
        op.f("ix_rom_measurements_analysis_id"),
        "rom_measurements",
        ["analysis_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Frozen catalog: definition data, never patient or demo data.
    import json
    from pathlib import Path

    data = json.loads(
        (Path(__file__).parent.parent / "data/protocols_v1.json").read_text(
            encoding="utf-8"
        )
    )
    metadata = sa.MetaData()
    tables = {
        name: sa.Table(name, metadata, autoload_with=op.get_bind())
        for name in (
            "protocol_categories",
            "protocols",
            "protocol_versions",
            "protocol_steps",
        )
    }
    op.bulk_insert(tables["protocol_categories"], data["categories"])
    for definition in data["protocols"]:
        key = definition["id"]
        version_id = key + "@" + definition["version"]
        op.bulk_insert(
            tables["protocols"],
            [
                {
                    "id": key,
                    "category_id": definition["category_id"],
                    "name": definition["name"],
                }
            ],
        )
        op.bulk_insert(
            tables["protocol_versions"],
            [
                {
                    "id": version_id,
                    "protocol_id": key,
                    "version": definition["version"],
                    "definition": definition,
                }
            ],
        )
        op.bulk_insert(
            tables["protocol_steps"],
            [
                {
                    "id": version_id + ":" + step["key"],
                    "version_id": version_id,
                    "key": step["key"],
                    "position": i,
                    "definition": step,
                }
                for i, step in enumerate(definition["steps"])
            ],
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rom_measurements_analysis_id"), table_name="rom_measurements"
    )
    op.drop_table("rom_measurements")
    op.drop_index(
        op.f("ix_assessment_step_results_assessment_protocol_id"),
        table_name="assessment_step_results",
    )
    op.drop_table("assessment_step_results")
    op.drop_table("rom_sessions")
    op.drop_index(op.f("ix_protocol_steps_version_id"), table_name="protocol_steps")
    op.drop_table("protocol_steps")
    op.drop_table("assessment_protocols")
    op.drop_index(
        op.f("ix_protocol_versions_protocol_id"), table_name="protocol_versions"
    )
    op.drop_table("protocol_versions")
    op.drop_table("protocols")
    op.drop_table("protocol_categories")
    # ### end Alembic commands ###
