"""motion_protocols_and_durable_jobs

Revision ID: 8b3675a1a316
Revises: aedc54d62754
"""

import sqlalchemy as sa
from alembic import op

revision = "8b3675a1a316"
down_revision = "aedc54d62754"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["assessment_media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_id"),
    )
    op.create_index(
        op.f("ix_processing_jobs_assessment_id"),
        "processing_jobs",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processing_jobs_state"), "processing_jobs", ["state"], unique=False
    )
    op.add_column(
        "analyses", sa.Column("motion", sa.JSON(), server_default="{}", nullable=False)
    )
    op.add_column(
        "assessment_media",
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
    )
    op.add_column(
        "assessments",
        sa.Column(
            "protocol", sa.String(length=40), server_default="static", nullable=False
        ),
    )
    op.add_column(
        "assessments",
        sa.Column(
            "side", sa.String(length=20), server_default="bilateral", nullable=False
        ),
    )
    op.add_column(
        "pose_frames",
        sa.Column("measurements", sa.JSON(), server_default="{}", nullable=False),
    )
    op.add_column(
        "pose_frames",
        sa.Column(
            "phase",
            sa.String(length=30),
            server_default="not_applicable",
            nullable=False,
        ),
    )
    op.add_column(
        "pose_frames",
        sa.Column("quality", sa.JSON(), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pose_frames", "quality")
    op.drop_column("pose_frames", "phase")
    op.drop_column("pose_frames", "measurements")
    op.drop_column("assessments", "side")
    op.drop_column("assessments", "protocol")
    op.drop_column("assessment_media", "metadata_json")
    op.drop_column("analyses", "motion")
    op.drop_index(op.f("ix_processing_jobs_state"), table_name="processing_jobs")
    op.drop_index(
        op.f("ix_processing_jobs_assessment_id"), table_name="processing_jobs"
    )
    op.drop_table("processing_jobs")
    # ### end Alembic commands ###
